{% set name = "ligo-proxy-utils" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ae78114e38852bdd48a3c4ba1af515843630efe4a45ff6eea5f9dd7038af0e85

build:
  number: 0
  noarch: python
  entry_points:
    - ligo-proxy-init = ligo_proxy_utils.ligo_proxy_init:ligo_proxy_init
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # build
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    # automagic manpage generation
    - argparse-manpage
    - ciecplib
  run:
    - ciecplib
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - python -m pytest --pyargs ligo_proxy_utils
    - ligo-proxy-init --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://wiki.ligo.org/AuthProject
  dev_url: https://git.ligo.org/computing/iam/ligo-proxy-utils.git
  doc_url: https://computing.docs.ligo.org/iam/ligo-proxy-utils/
  summary: Utilities for obtaining short-lived proxy certificates for LIGO
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
